require File.expand_path('../lib/omniauth/version', __FILE__)

source 'http://rubygems.org'

# gem 'oa-core', OmniAuth::Version::STRING, :path => '../oa-core', :require => 'omniauth/core'
# 
# /Users/saimon/Development/Clients/teambox_omniauth
gem 'oa-core', '~> 0.3.2'
gem 'oa-oauth', '~> 0.3.2'

platforms :jruby do
  gem 'jruby-openssl', '~> 0.7'
end

gemspec
